Update main.py
common-workflow-language/cwltool pull request #1390
Opened 2020-12-14 17:08 UTC by leipzig

If Ruamel encounters a blank comment string "" instead of None it throws a hissy fit. This happened for me when an input was of type 'Record'
```
  read_names:
    type:
      - type: record
```

```
Traceback (most recent call last):
  File "~/dev/capanno-utils/lib/python3.6/site-packages/cwltool/main.py", line 972, in main
    make_template(tool)
  File "~/dev/capanno-utils/lib/python3.6/site-packages/cwltool/main.py", line 732, in make_template
    generate_input_template(tool),
  File "~/dev/capanno-utils/lib/python3.6/site-packages/cwltool/main.py", line 299, in generate_input_template
    template.insert(0, name, value, comment)
  File "~/dev/capanno-utils/lib/python3.6/site-packages/ruamel/yaml/comments.py", line 722, in insert
    self.yaml_add_eol_comment(comment, key=key)
  File "~/dev/capanno-utils/lib/python3.6/site-packages/ruamel/yaml/comments.py", line 294, in yaml_add_eol_comment
    if comment[0] != '#':
```

2020-12-14 17:35 UTC, mr-c requested changes
Thank you @leipzig ! Can you add a confirmatory test-case?

2020-12-14 19:29 UTC, leipzig commented
> Thank you @leipzig ! Can you add a confirmatory test-case?

OK I don't see any existing tests of `make_template` `generate_input_template` `generate_example_input` but I'll give it a go

2020-12-14 19:47 UTC, mr-c commented
> > Thank you @leipzig ! Can you add a confirmatory test-case?
> 
> OK I don't see any existing tests of `make_template` `generate_input_template` `generate_example_input` but I'll give it a go

Yeah, I'm setting you up to test previously under-tested code; good luck and please ask for help!

https://codecov.io/gh/common-workflow-language/cwltool/src/main/cwltool/main.py#L160

2022-01-06 12:41 UTC, mr-c approved these changes

2022-01-06 12:46 UTC, merged

2022-01-06 13:58 UTC, mr-c commented
Thanks @leipzig !