Fix erroneous URL encoding of final output filenames
common-workflow-language/cwltool pull request #1446
Opened 2021-05-18 23:40 UTC by AlexTate

Fixes #1445; command_line_tool.collect_output() now URL decodes output file `basename`s, and uses the decoded result to determine the `nameroot` and `nameext` fields

2021-05-19 15:11 UTC, mr-c requested changes
Thank you @AlexTate for this PR. Can you add a test to demonstrate the problem and the fix?

2021-05-21 10:17 UTC, mr-c requested changes
Please also run `make format` :-)

2021-05-27 10:27 UTC, mr-c requested changes
https://github.com/common-workflow-language/cwltool/pull/1446/files shows a couple lines without test coverage; can you investigate?

2021-05-27 10:28 UTC, mr-c commented on tests/test_path_checks.py
> +def test_clt_returns_specialchar_names(tmp_path: Path) -> None:
This needs a docstring: https://github.com/common-workflow-language/cwltool/pull/1446/checks?check_run_id=2668401511#step:7:26

2021-05-29 20:43 UTC, AlexTate commented
Of course. I can address both of these requests but it will be a little over a week before I have a chance to take a look.

2021-10-01 17:44 UTC, merged