fix --single-step step2_tool error
common-workflow-language/cwltool pull request #1597
Opened 2022-01-20 07:35 UTC by huzech

when use --single-step step2_tool parameter to run step in workflow meet this error
```
Traceback (most recent call last):
  File "/d/project/cwltool-main/cwltool/main.py", line 1181, in main
    ctool = choose_step(args, tool, loadingContext)
  File "/d/project/cwltool-main/cwltool/main.py", line 861, in choose_step
    extracted = get_step(tool, step_id, loading_context)
  File "/d/project/cwltool-main/cwltool/subgraph.py", line 225, in get_step
    name = outport.split("#")[-1].split("/")[-1]
AttributeError: 'CommentedMap' object has no attribute 'split'
```

2022-01-20 09:40 UTC, kinow reviewed
`mypy` is failing. But it also worked when I tried a `--single-step $param` for a workflow.

```bash
$ cwltool --debug --single-step step0 cwltool/schemas/v1.1/tests/count-lines11-extra-step-wf-noET.cwl /tmp/params.json
$ cat /tmp/params.json 
{
  "file1": {
    "class": "File",
    "location": "/tmp/foo.txt"
  }
}
```

2022-01-20 10:25 UTC, huzech commented
Thank your test! I use list steps format in cwl, it's not work, I'll try to fix it with both list and object formt step
```
class: Workflow
cwlVersion: v1.0
id: subgraph_wrokflow
label: subgraph_wrokflow
inputs:
  - id: input
    type: File?
    default:
      class: File
      path: /d/project/cwlsubgraphtest/1.txt
  - id: txt
    type: string?
    default: step1
  - id: txt_1
    type: string?
    default: step2
  - id: txt_2
    type: string?
    default: step3
outputs:
  - id: output1
    outputSource:
      - step1_tool/output1
    type: File
  - id: output4
    outputSource:
      - step3_tool/output1
    type: File
  - id: output2
    outputSource:
      - step2_tool/output1
    type: File
steps:
  - id: step1_tool
    in:
      - id: input
        source: input
      - id: txt
        default: step1
        source: txt
    out:
      - id: output1
      - id: output2
    run: ./add_txt_to_file.cwl
    label: add_txt_to_file
  - id: step2_tool
    in:
      - id: input
        source: step1_tool/output2
      - id: txt
        default: step2
        source: txt_1
    out:
      - id: output1
      - id: output2
    run: ./add_txt_to_file.cwl
    label: add_txt_to_file
  - id: step3_tool
    in:
      - id: input
        source: step2_tool/output2
      - id: txt
        default: step3
        source: txt_2
    out:
      - id: output1
      - id: output2
    run: ./add_txt_to_file.cwl
    label: add_txt_to_file
requirements: []

```

2022-01-20 12:37 UTC, mr-c requested changes
Thank you @huzech for this. Can you add your test case to the PR so we can confirm the fix and prevent regressions in the future?

2022-01-29 12:57 UTC, mr-c approved these changes

2022-01-29 17:24 UTC, merged