Process generator docs
common-workflow-language/cwltool pull request #1599
Opened 2022-01-20 15:02 UTC by tetron

Add page describing the ProcessGenerator extension.

2022-01-20 15:35 UTC, mr-c requested changes
`docs/processgen.rst: WARNING: document isn't included in any toctree` :-)

2022-01-24 16:14 UTC, tetron commented
I didn't dig too far into trying to generate the docs, but it doesn't seem like we have a `make doc-dev` or something that installs sphinx and all the correct plugins.

Does it get auto-built somewhere?  Long term we should be migrating to a proper doc tree but right now it is very incomplete, including how to add to it.

2022-01-24 16:50 UTC, mr-c commented
> I didn't dig too far into trying to generate the docs, but it doesn't seem like we have a `make doc-dev` or something that installs sphinx and all the correct plugins.

Okay, I've added a Makefile target so that `make install-doc-dep docs` works

> Does it get auto-built somewhere?

There is a Read the Docs autobuilder enabled for each PR

The current build is https://cwltool--1599.org.readthedocs.build/en/1599/

Though it doesn't show the log unless it fails. To find the log I had to go to https://readthedocs.org/projects/cwltool/builds/ → https://readthedocs.org/projects/cwltool/builds/15866894/ → "view raw" https://readthedocs.org/api/v2/build/15866894.txt

>  Long term we should be migrating to a proper doc tree but right now it is very incomplete, including how to add to it.

`processgen` is the first piece of non-autogenerated doc :-) I've added it to the existing table of contents

2022-01-24 16:51 UTC, mr-c commented
https://cwltool--1599.org.readthedocs.build/en/1599/processgen.html

2022-01-24 16:53 UTC, mr-c requested changes
Otherwise, LGTM!

2022-01-24 16:53 UTC, mr-c commented on docs/processgen.rst
> +Experimental feature.
```suggestion
Experimental feature and unofficial extension to the CWL standards.
```

2022-01-24 16:54 UTC, tetron commented
Ah, this is good, actually.

To bootstrap proper documentation, it probably wouldn't be too hard to break up the current README into sections.  That's another ticket, though.

2022-01-24 18:36 UTC, mr-c approved these changes

2022-01-24 19:43 UTC, merged