Revert "Drop Python 3.6"
common-workflow-language/cwltool pull request #1620
Opened 2022-02-14 21:18 UTC by tetron

Ubuntu 18.04 (LTS, supported until April 2023) and Centos 7 are still
on Python 3.6.

This reverts commit 780f64a71fd9778d8481ede998c9c3da91bce4aa.

2022-02-15 02:04 UTC, tom-tan commented
CentOS 7 is supported until [Jun 30th, 2024](https://www.centos.org/download/).
It needs an effort to support Python 3.6 for another two years.

Fortunately we already have [venv](https://docs.python.org/3/library/venv.html) as a workaround of this issue and it is documented in the [README of cwltool](https://github.com/common-workflow-language/cwltool#install).

Are there reasons to directly support OS built-in version of Python rather than encouraging to use `venv`?

2022-02-15 08:32 UTC, mr-c commented
> Ubuntu 18.04 (LTS, supported until April 2023) and Centos 7 are still
> on Python 3.6.

Ubuntu 18.04 (Bionic Beaver) ships Python 3.7 and 3.8

https://packages.ubuntu.com/search?suite=bionic&keywords=python3.7

https://packages.ubuntu.com/search?suite=bionic&keywords=python3.8

So `sudo apt install python3.8 && python3.8 -m pip install --user cwltool` should work

Python 3.8 can be added to CentOS from their official repos:

> 1.Install CentOS SCLo RH repository:
>
>    `yum install centos-release-scl-rh`
>
> 2. Install rh-python38-python rpm package:
>
>    `yum install rh-python38-python`

From https://centos.pkgs.org/7/centos-sclo-rh-x86_64/rh-python38-python-3.8.6-1.el7.x86_64.rpm.html

I would be more interested in a PR adding these instructions to the docs. Bonus if there is a variation of https://github.com/common-workflow-language/cwltool/blob/main/cwltool.Dockerfile for Ubuntu 18.04 and CentOS 7 demonstrating that this works.

And speaking of the docs, this is a good time to start breaking up the giant README.rst and move the installation instructions to their own page, like was done for https://cwltool.readthedocs.io/en/latest/processgen.html

2022-02-15 08:37 UTC, mr-c requested changes
I prefer we document how to install on CentOS 7 and Ubuntu 18.04 using the available systems packages.

2022-02-15 08:37 UTC, mr-c commented on README.rst
> +``tox -e py36-unit -- -v tests/test_examples.py::test_scandeps``
No reason to change this

2022-02-15 08:37 UTC, mr-c commented on cwltool/job.py
> +    DirectoryType,
? Probably best to run `make sort-imports`

2022-02-15 08:37 UTC, mr-c commented on setup.py
> -        "Programming Language :: Python :: 3.10",
We still support Python 3.10

2022-02-15 08:37 UTC, mr-c commented on tox.ini
> +  py3{5,7,8,9,10}-!{unit,mypy,lintreadme} = True
6 not 5

2022-02-15 16:05 UTC, tetron commented
@mr-c we're looking into building on ubuntu 18.04 and centos 7 packages with a more recent python.  I'm going to keep this PR open until we have a solution.

2022-02-15 16:16 UTC, cure commented
I would really like to seem more process around the depreciation of Python versions. This is not the first time we run into this. Changes like these seem extremely arbitrary, and they cause a pile of sudden, urgent work for no good reason.

Depreciations should not happen suddenly and there should be a sufficient amount of warning. 

Obviously, the "upstream stopped supported security updates" argument carries some weight. However, it is not that simple, and it's not true, because distributions do provide security fixes for older Python versions, especially the ones they ship with by default (e.g. Ubuntu 18.04, where Python 3.6 is the default "python3" package).

2022-02-15 16:53 UTC, mr-c commented
@cure Sure, I agree a formal policy would be nice. Would you like to start a draft PR that we could send around to the other users of `cwltool` to review?

Here is shared policy of Matplotlib, scikit-learn, IPython, Jupyter, yt, SciPy, NumPy, and scikit-image as a starting point:

https://numpy.org/neps/nep-0029-deprecation_policy.html

FYI, Conda (Anaconda and conda-forge) and Debian have both moved on from Python 3.6, and as I'm the maintainer of the `cwltool` packages for both, it is problematic to carry on additional old version of Python when there are other alternatives.

https://conda.io/en/latest/miniconda.html

2022-02-15 22:32 UTC, tetron commented
> Sure, I agree a formal policy would be nice. Would you like to start a draft PR that we could send around to the other users of cwltool to review?

proposed a policy at PR #1621

>  FYI, Conda (Anaconda and conda-forge) and Debian have both moved on from Python 3.6, and as I'm the maintainer of the cwltool packages for both, it is problematic to carry on additional old version of Python when there are other alternatives.

If it happens in the future that an essential dependency is only available for Python 3.7+ and this is a problem for packaging then we will need to examine our options, but I don't think preemptively dropping support for Python 3.6 is the right way to go about it.

2022-02-17 19:08 UTC, mr-c approved these changes

2022-02-17 19:08 UTC, merged