print-dot: Removed primary path prefix from graph labels
common-workflow-language/cwltool pull request #1647
Opened 2022-03-23 14:33 UTC by RenskeW

Removed primary file path prefix from graph labels

2022-03-25 20:16 UTC, RenskeW commented
Made some changes in test_print_dot() so expected output now corresponds to computed output.

2022-03-26 12:24 UTC, mr-c commented on tests/test_examples.py
> +        (source, target)
```suggestion
        (source, target)
```

This cause the CI tests to fail. Fixable via `make format`

2022-03-26 12:32 UTC, mr-c requested changes
Please run `make format` :-)

2022-03-26 15:48 UTC, RenskeW commented
Thanks! 😃

2022-03-29 09:56 UTC, mr-c approved these changes

2022-03-29 09:57 UTC, merged