Exclude children of subdirectories from symlink
common-workflow-language/cwltool pull request #1690
Opened 2022-07-13 22:20 UTC by jfennick

This PR (hopefully) fixes #1029.

2022-07-13 22:37 UTC, mr-c commented
Thanks for this! The lint error is being fixed over in https://github.com/common-workflow-language/cwltool/pull/1691

2022-07-14 18:22 UTC, jfennick commented
It looks like my change is breaking some other examples, but I'm a bit lost. Is anyone willing to take a look and help push this PR across the finish line?

2022-07-14 18:37 UTC, mr-c commented
Here is one of the conformance tests, that now fail

```
cwltool v1.0/cat-from-dir.cwl v1.0/cat-from-dir-with-literal-file.yaml
Pipe to stdin from literal File via a Directory literal
Returned non-zero
ERROR'cat' not found: [Errno 2] No such file or directory: "I'm a File literal; howdy!"
WARNING[job cat-from-dir.cwl] completed permanentFail
WARNINGFinal process status is permanentFail
```

2022-07-14 19:52 UTC, jfennick commented
Yes, I read through the logs. I was asking if any of the maintainers are willing to help fix the errors.

2022-07-14 20:42 UTC, kinow reviewed
Debugged the test @mr-c linked, and suggested a possible fix for @jfennick.

@jfennick maybe we should include the test from #1029 as a unit test here?

Hope that helps!
-Bruno

2022-07-14 20:42 UTC, kinow commented on cwltool/pathmapper.py
> +            if entry.type in ("File", "Directory"):
@jfennick I think this line can be removed. Debugging the conformance test that @mr-c pointed is failing, I noticed that the `File` to be staged by the workflow is a `CreateFile` (which I was not familiar with, but the code comments help clarify it, I think - <https://github.com/common-workflow-language/cwltool/blob/3945a18c699c3ca500a9343c40b34db966c6787b/cwltool/pathmapper.py#L48-L49>).

After I removed that line, the test `cat-from-dir.cwl` passed, and the workflow `test.cwl` in #1029 also passed with no errors (I switched to `main` and confirmed it failed for me too there).

2022-07-14 21:20 UTC, mr-c requested changes
Looks great! It will need a confirmatory test.

2022-07-14 22:38 UTC, mr-c commented
Try `make install-dep format`

2022-07-14 23:47 UTC, mr-c approved these changes

2022-07-14 23:57 UTC, mr-c commented on cwltool/pathmapper.py
> +    def items_exclude_children(self) -> List[Tuple[str, MapperEnt]]:
FYI @tetron @DailyDreaming @kellrott  about this proposed addition to PathMapper

2022-07-15 00:07 UTC, jfennick commented
> Try `make install-dep format`

Sorry for blasting your CI for trivial formatting, but I was running into nasty installation errors when trying to run it locally using the instructions in the readme. If I can reproduce, I'll try to open another issue.

2022-07-15 00:14 UTC, mr-c commented
> > Try `make install-dep format`
> 
> Sorry for blasting your CI for trivial formatting, but I was running into nasty installation errors when trying to run it locally using the instructions in the readme. If I can reproduce, I'll try to open another issue.

S'alright. New commits will cancel old CI jobs automatically.

Did you have a dedicated Python virtualenv active before running those commands?

2022-07-15 00:21 UTC, kinow approved these changes

2022-07-15 00:40 UTC, jfennick commented
> > > Try `make install-dep format`
> > 
> > 
> > Sorry for blasting your CI for trivial formatting, but I was running into nasty installation errors when trying to run it locally using the instructions in the readme. If I can reproduce, I'll try to open another issue.
> 
> S'alright. New commits will cancel old CI jobs automatically.
> 
> Did you have a dedicated Python virtualenv active before running those commands?

I created a new conda environment. See #1694

2022-07-15 03:54 UTC, merged