Added loop support
common-workflow-language/cwltool pull request #1779
Opened 2022-12-25 12:18 UTC by GlassOfWhiskey

This commit converts the logic introduced to handle the `cwltool:Loop` requirement extension to handle the new `loop` construct introduced in the CWL v1.3 spec.
A proper method in the `upgrade.py` module handles the automatic conversion from the old requirement to the new format.
The existing `test_loop.py` file is still useful to verify the correctness of the conversion process.

2022-12-26 10:23 UTC, mr-c requested changes
Huzzah!

You'll also need to add a dump of the `v1.3.0-dev1` schema to https://github.com/common-workflow-language/cwltool/tree/cwl-v1.3/cwltool/schemas

2022-12-26 10:23 UTC, mr-c commented on cwltool/update.py
> +def v1_2to1_3(
There is no CWL v1.3 yet, only `v1.3.0-dev1`

2022-12-26 10:23 UTC, mr-c commented on cwltool/update.py
> +INTERNAL_VERSION = "v1.3"
```suggestion
INTERNAL_VERSION = "v1.3.0-dev1"
```

See the https://github.com/common-workflow-language/cwltool/blob/f0a844af6f93883fcacb3572a6366124a50d0909/cwltool/update.py#LL222

2022-12-30 09:39 UTC, mr-c requested changes

2022-12-30 09:39 UTC, mr-c commented on cwltool/update.py
> +                            raise SourceLine(
Test case for this, please

2022-12-30 09:39 UTC, mr-c commented on cwltool/update.py
> +                    r["class"] = rewrite[cls]
This line has no test coverage.

2024-07-10 01:13 UTC, tetron commented
With the fix in https://github.com/common-workflow-language/schema_salad/pull/846 this passes unit tests for me.

2024-07-10 06:34 UTC, mr-c commented
I didn't think you meant to close this PR @tetron 🙂

2024-07-10 13:45 UTC, tetron commented
> I didn't think you meant to close this PR @tetron 🙂

github seems to have done it automatically :frowning_face:

2024-07-10 18:16 UTC, mr-c commented
@tetron I think those may be due to recent changes to `cwltest`:  https://github.com/common-workflow-language/cwltest/issues/216

Did you see my email about the cofest?

2024-07-11 15:07 UTC, tetron commented
Ok!  So we're just down to the test coverage check.

2024-07-16 22:35 UTC, tetron commented
I keep fiddling with this but I think we should just override the codecov check because at least one of the lines it is complaining about appears to be almost impossible to trigger in normal usage because it is an exception handler and "normal" exceptions get routed another way, so it only engages if a very truly unexpected case happens.  Possibly we could mock something but I'm pretty sure at this point the cost/benefit of trying to make codecov happy for these corner cases is very bad.

I haven't yet managed to determine if there's a way to tell codecov to ignore certain lines.

2024-07-17 14:24 UTC, mr-c approved these changes

2024-07-17 17:04 UTC, merged