patch dockerFile build
common-workflow-language/cwltool pull request #1979
Opened 2024-02-26 21:01 UTC by misterbrandonwalker

Don't let dockerFile tag be dependent on force_pull or pull_image booleans

2024-02-27 12:56 UTC, mr-c requested changes
Thank you @misterbrandonwalker ; can you add a test to confirm this fix?

2024-05-08 07:34 UTC, merged

2024-05-08 07:35 UTC, mr-c commented
Thank you @misterbrandonwalker !

2024-05-08 13:18 UTC, misterbrandonwalker commented
[heart]         Brandon Walker reacted to your message:
________________________________
From: Michael R. Crusoe ***@***.***>
Sent: Wednesday, May 8, 2024 7:35:57 AM
To: common-workflow-language/cwltool ***@***.***>
Cc: Brandon Walker ***@***.***>; Mention ***@***.***>
Subject: Re: [common-workflow-language/cwltool] patch dockerFile build (PR #1979)


Thank you @misterbrandonwalker<https://github.com/misterbrandonwalker> !

—
Reply to this email directly, view it on GitHub<https://github.com/common-workflow-language/cwltool/pull/1979#issuecomment-2099937452>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AKNB26N4DCKONW4CAQ2WQTTZBHIV3AVCNFSM6AAAAABD25AQUKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAOJZHEZTONBVGI>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2025-11-05 15:08 UTC, davidjsherman commented
@mr-c 
Previously, if the container image named in `dockerImageId` was found, then the image was not built: the instructions in `dockerFile` were used only if needed. With this change, a new image is built regardless, whenever `dockerFile` is present.

Is this intentional? That is, does the language in [5.5 DockerRequitrement](https://www.commonwl.org/v1.0/CommandLineTool.html#DockerRequirement)

> dockerFile optional string Supply the contents of a Dockerfile which will be built using docker build.

mean that the image _MUST_ be built if `dockerFile` is specified, not _MAY_ be built if `dockerImageId` is not found?

We provide `dockerFile` in our CommandLineTools as a backup for when the image is not already present, but with Podman we are finding that our images are rebuilt at every execution of the tool.

Thanks in advance for the clarification